In [6]:
import math
import numpy as np
import pandas as pd
from sklearn import linear_model
from word2number import w2n

In [7]:
df = pd.read_csv('hiring_multi.csv')#reading multivariable data from csv 
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [8]:
numbers={} #replacing the number words to numbers by creating a dictionary 
numbers={'one':1,'two':2,'three':3,'four':4,'five':5,'six':6,'seven':7,'eight':8,'nine':9,'ten':10,'eleven':11}
n=0
for i in df.experience:
    if i in numbers:
        df.loc[n, ('experience')]=numbers[i]
    n=n+1
        
df        

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2          5         6.0                7   60000
3          2        10.0               10   65000
4          7         9.0                6   70000
5          3         7.0               10   62000
6         10         NaN                7   72000
7         11         7.0                8   80000

In [9]:
n=0   ##using the word2number module!!!!!!!
for i in df.experience:
    if not pd.isna(i):
        j=w2n.word_to_num(i)
        df.loc[n, ('experience')]=j
    n=n+1
df

ValueError: Type of input is not string! Please enter a valid number word (eg. 'two million twenty three thousand and forty nine')

In [10]:
df.experience=df.experience.fillna(0)# replacing the missing values with 0
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         NaN                7   72000
7          11         7.0                8   80000

In [11]:
median_testscore=math.floor(df.test_score.median())# replacing the missing values with the median
print("median=",median_testscore)
df.test_score=df.test_score.fillna(median_testscore)
df

median= 8


experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [12]:
reg=linear_model.LinearRegression()
reg.fit(df[['experience','test_score','interview_score']],df.salary)

LinearRegression()

In [13]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [14]:
reg.intercept_

17737.26346433771

In [15]:
reg.predict([[5,9,5]])

C:\Users\Sankalp Mallappa\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([59439.59243086])

In [17]:
import pickle
with open('model_pickle','wb') as f:
    pickle.dump(reg,f)
with open('model_pickle','rb') as f:
    msaved=pickle.load(f)
msaved.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [18]:
# from sklearn.externals import joblib

ImportError: cannot import name 'joblib' from 'sklearn.externals' (C:\Users\Sankalp Mallappa\anaconda3\lib\site-packages\sklearn\externals\__init__.py)